export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO';
export const REGISTRAR_USUARIO_EXITO = 'REGISTRAR_USUARIO_EXITO';
export const REGISTRAR_USUARIO_ERROR = 'REGISTRAR_USUARIO_ERROR';

export const LOGEAR_USUARIO = 'LOGEAR_USUARIO';
export const LOGEAR_USUARIO_EXITO = 'LOGEAR_USUARIO_EXITO';
export const LOGEAR_USUARIO_ERROR = 'LOGEAR_USUARIO_ERROR';

export const CERRAR_SESION = 'CERRAR_SESION';