export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const CARGA_PRODUCTOS = 'CARGA_PRODUCTOS';
export const CARGA_PRODUCTOS_EXITO = 'CARGA_PRODUCTOS_EXITO';
export const CARGA_PRODUCTOS_ERROR = 'CARGA_PRODUCTOS_ERROR';

export const PRODUCTO_ELIMINAR = 'PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const PRODUCTO_EDITAR = 'PRODUCTO_EDITAR';
export const PRODUCTO_EDITAR_COMENZAR = 'PRODUCTO_EDITAR_COMENZAR';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';